# Generated by Django 4.2.5 on 2023-10-07 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beat',
            name='drums',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='beat',
            name='melody',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
